# 数据库监控配置示例
db:
  monitor:
    # 是否启用数据库监控功能
    enabled: true
    
    # 数据源名称（如果不指定则使用默认数据源）
    data-source-name: primary
    
    # 需要监控的表名列表，支持通配符
    table-names:
      - user_*      # 匹配所有以 user_ 开头的表
      - order_info  # 精确匹配 order_info 表
      - product_*   # 匹配所有以 product_ 开头的表
    
    # 监控时间间隔配置
    time-interval:
      type: MINUTES    # 时间间隔类型：MINUTES, HOURS, DAYS
      value: 10        # 时间间隔值：近10分钟
    
    # XXL-Job配置
    xxl-job:
      enabled: false                                    # 是否启用XXL-Job调度
      admin-addresses: http://localhost:8080/xxl-job-admin  # XXL-Job管理后台地址
      app-name: db-monitor-executor                     # 应用名称
      address:                                          # 注册地址
      ip:                                               # 执行器IP
      port: 9999                                        # 执行器端口号
      access-token:                                     # 执行器通信TOKEN
      log-path: /data/applogs/xxl-job/jobhandler       # 执行器日志路径
      log-retention-days: 30                            # 执行器日志文件保存天数
      cron: 0 */10 * * * ?                             # 调度任务Cron表达式
    
    # 监控数据表配置
    monitor-table:
      table-name: db_monitor_statistics  # 监控数据表名
      auto-create: true                  # 是否自动创建表
      retention-days: 30                 # 数据保留天数
    
    # 指标暴露配置
    metrics:
      enabled: true       # 是否启用指标暴露
      prefix: db_monitor  # 指标前缀
      endpoint: /metrics  # 暴露端点路径
    
    # 磁盘大小估算配置
    disk-size:
      enabled: true                    # 是否启用磁盘大小估算
      default-row-size-bytes: 100      # 默认行大小（字节）
      index-overhead-ratio: 0.25       # 索引开销比例（相对于数据大小）
      storage-overhead-ratio: 0.3      # 存储开销比例（相对于理论大小）
      cache-enabled: true              # 是否缓存平均行大小
      cache-expiration-minutes: 60     # 缓存过期时间（分钟）

# Spring Boot Actuator配置（可选）
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 数据源配置示例
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# 日志配置
logging:
  level:
    com.github.starter.dbmonitor: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE