# 数据库监控配置示例
db:
  monitor:
    # 是否启用数据库监控功能
    enabled: true
    
    # 数据源名称（如果不指定则使用默认数据源）
    data-source-name: primary
    
    # 需要监控的表名列表，支持通配符
    table-names:
      - user_*      # 匹配所有以 user_ 开头的表
      - order_info  # 精确匹配 order_info 表
      - product_*   # 匹配所有以 product_ 开头的表
    
    # 监控时间间隔配置
    time-interval:
      type: MINUTES    # 时间间隔类型：MINUTES, HOURS, DAYS
      value: 10        # 时间间隔值：近10分钟
    
    # XXL-Job配置
    xxl-job:
      enabled: false                                    # 是否启用XXL-Job调度
      admin-addresses: http://localhost:8080/xxl-job-admin  # XXL-Job管理后台地址
      app-name: db-monitor-executor                     # 应用名称
      address:                                          # 注册地址
      ip:                                               # 执行器IP
      port: 9999                                        # 执行器端口号
      access-token:                                     # 执行器通信TOKEN
      log-path: /data/applogs/xxl-job/jobhandler       # 执行器日志路径
      log-retention-days: 30                            # 执行器日志文件保存天数
      cron: 0 */10 * * * ?                             # 调度任务Cron表达式
    
    # 监控数据表配置
    monitor-table:
      table-name: db_monitor_statistics  # 监控数据表名
      auto-create: true                  # 是否自动创建表
      retention-days: 30                 # 数据保留天数
    
    # 指标暴露配置
    metrics:
      enabled: true       # 是否启用指标暴露
      prefix: db_monitor  # 指标前缀
      endpoint: /metrics  # 暴露端点路径

# Spring Boot Actuator配置（可选）
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 数据源配置示例
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # MyBatis配置
  mybatis:
    # 指定mapper映射文件位置
    mapper-locations: classpath:mapper/*.xml
    # 指定实体类包名
    type-aliases-package: com.github.starter.dbmonitor.entity
    # 开启驼峰命名转换
    configuration:
      map-underscore-to-camel-case: true
      # 开启二级缓存
      cache-enabled: true
      # 开启延迟加载
      lazy-loading-enabled: true
      # 开启积极延迟加载
      aggressive-lazy-loading: false
      # 允许多种结果集从单条语句返回
      multiple-result-sets-enabled: true
      # 允许JDBC支持自动生成主键
      use-generated-keys: true
      # 使用列别名替换列名
      use-column-label: true
      # 禁用自动映射
      auto-mapping-behavior: partial
      # 指定发现自动映射目标未知列的行为
      auto-mapping-unknown-column-behavior: warning
      # 配置默认的执行器
      default-executor-type: simple
      # 指定默认超时时间
      default-statement-timeout: 25
      # 指定默认获取数据的数量
      default-fetch-size: 100
      # 允许在嵌套语句中使用分页
      safe-row-bounds-enabled: false
      # 允许在嵌套语句中使用分页
      safe-result-handler-enabled: true
      # 是否开启自动驼峰命名规则映射
      map-underscore-to-camel-case: true
      # 本地缓存机制
      local-cache-scope: session
      # 当没有为参数提供特定的JDBC类型时，为空值指定JDBC类型
      jdbc-type-for-null: other
      # 指定哪个对象的方法触发一次延迟加载
      lazy-load-trigger-methods: equals,clone,hashCode,toString
      # 指定动态SQL中数据库标识符的默认语言
      default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
      # 指定当结果集中值为null的时候是否调用映射对象的setter方法
      call-setters-on-nulls: false
      # 指定MyBatis是否以及如何自动映射指定的列到字段/属性
      return-instance-for-empty-row: false
      # 指定MyBatis日志的具体实现
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.github.starter.dbmonitor: INFO
    com.github.starter.dbmonitor.repository: DEBUG
    org.apache.ibatis.logging: DEBUG