server:
  port: 8080

spring:
  application:
    name: db-monitor-example
  
  # H2数据库配置（用于演示）
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

# 数据库监控配置
db:
  monitor:
    enabled: true
    data-source-name: dataSource
    table-names:
      - user_*
      - order_info
      - product_*
    time-interval:
      type: MINUTES
      value: 1  # 1分钟间隔用于演示
    xxl-job:
      enabled: false
    monitor-table:
      table-name: db_monitor_statistics
      auto-create: true
      retention-days: 7
    metrics:
      enabled: true
      prefix: db_monitor
      endpoint: /metrics
    disk-size:
      enabled: true
      default-row-size-bytes: 100
      index-overhead-ratio: 0.25
      storage-overhead-ratio: 0.3
      cache-enabled: true
      cache-expiration-minutes: 60

# Spring Boot Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    com.github.starter.dbmonitor: DEBUG
    com.example: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE